export default {
  userStatus: `http://localhost:3005/user/status`,
  authenticationByApi: `http://localhost:3005/authentication/api`,
  authenticationByMercadolibre: `http://localhost:3005/authentication/meli`,
  siteCategories: `http://localhost:3005/site/categories`,
  favorites: `http://localhost:3005/user/favorite`,
  userBought: `http://localhost:3005/user/bought`,
  itemsCategories: `http://localhost:3005/products/items/categories`,
  userCart: "http://localhost:3005/user/cart",
  register: `http://localhost:3005/authentication/register`,
  registerConfirm: `http://localhost:3005/authentication/register/confirm`,
  item: "http://localhost:3005/products/item",
  items: "http://localhost:3005/products/items",
  analytics: "http://localhost:3005/site/analytic",
  history: "http://localhost:3005/user/history",
  seller: `http://localhost:3005/products/product/seller`,
  description: `http://localhost:3005/products/item/description`,
  questions: `http://localhost:3005/products/product/questions`,
  myQuestion: `http://localhost:3005/user/myquestion`,
  opinions: `http://localhost:3005/products/item/opinions`,
  userProfileSeller: "http://localhost:3005/user/seller/profile",
  userProfile: `http://localhost:3005/user/me`,
  sites: "http://localhost:3005/site/sites",
  myReport: "http://localhost:3005/user/myreport",
  PDF: "http://localhost:3005/user/boughtsPDF",
  opinionByProduct: "http://localhost:3005/user/opinion/byproduct",
  myOpinion: `http://localhost:3005/user/myopinion`,
};
